package stu;




import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 *
 */
@WebService(name = "EtudiantWService", targetNamespace = "http://serveur/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface EtudiantWService {


    /**
     *
     * @return
     *     returns java.util.List<stub.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtudiants", targetNamespace = "http://serveur/", className = "stub.GetEtudiants")
    @ResponseWrapper(localName = "getEtudiantsResponse", targetNamespace = "http://serveur/", className = "stub.GetEtudiantsResponse")
    @Action(input = "http://serveur/EtudiantWService/getEtudiantsRequest", output = "http://serveur/EtudiantWService/getEtudiantsResponse")
    public List<Student> getEtudiants();

}